export default function AboutPage() {
  return (
    <div className="space-y-8 max-w-3xl">
      {/* Page Title */}
      <div>
        <h1 className="text-3xl font-semibold tracking-tight text-zinc-900">
          About PHILHARMONIC DB
        </h1>
        <p className="mt-2 text-sm text-zinc-500">
          Background, documentation, and asset workflows.
        </p>
      </div>

      <hr className="border-zinc-200" />

      {/* Section 1: Overview */}
      <section className="space-y-3">
        <h2 className="text-xl font-semibold tracking-tight text-zinc-800">
          Purpose
        </h2>
        <p className="text-zinc-600 leading-relaxed text-sm">
          Functional genomics remains heavily biased toward a handful of model organisms. 
          Over 90% of experimentally validated protein functions derive from fewer than 10 species, 
          yet the majority of biodiversity—including ecologically critical taxa 
          (corals, symbiotic dinoflagellates), agriculturally important species, 
          and human pathogens—lacks reliable functional annotation. PHILHARMONIC DB addresses this gap 
          through "guilt-by-association" network inference, requiring only a sequenced proteome to 
          produce functional predictions. This resource will enable: (i) hypothesis generation for 
          unstudied organisms, (ii) comparative functional genomics across deep evolutionary timescales, 
          (iii) identification of lineage-specific pathway innovations, and (iv) prioritization of genes 
          for experimental follow-up in non-model systems. The dataset directly supports ongoing work 
          in agricultural biology, coral reef biology, veterinary genomics, and pathogen biology.
        </p>
        <p className="text-zinc-600 leading-relaxed text-sm">
          This project is a collaboration of the Computation and Biology Group (PI: Bonnie Berger) at MIT,
          The Bioinfrmaics and Computational Biology Group (PI: Lenore Cowen) Lab at Tufts, 
          and the Machine Leanring Lab (PI: Adam Klivans) at UT Austin.
          Support is provided by NIH R35 MIRA grant 1R35GM141861, NSF grant 2531917, NSF GRFP 2141064, 
          and the NSF AI institute for Foundations of Machine Learning for GPU support.
        </p>

        <p className="text-zinc-600 leading-relaxed text-sm">
          To browse the list of available species, <a 
              href="/philharmonicDB/preprocessed_data/species/" 
              className="text-emerald-600 hover:underline"
            >
              click here
            </a>. 
        </p>        
      </section>

{/* Section 2: How to use this database */}
      <section className="space-y-5">
        <h2 className="text-xl font-semibold tracking-tight text-zinc-800">
          How to use this database
        </h2>
        <p className="text-zinc-600 leading-relaxed text-sm">
          This platform is designed to provide seamless web-based exploration of large-scale 
          functionally-annotated clusters generated by  the{" "}
            <a 
              href="https://github.com/samsledje/philharmonic" 
              target="_blank" 
              rel="noreferrer" 
              className="text-emerald-600 hover:underline"
            >
              PHILHARMONIC pipeline
            </a>. You can navigate through our data using the 
          following data resolution:
        </p>

        {/* Subsection A: Browse species */}
        <div className="space-y-2 pl-4 border-l-2 border-zinc-100">
          <h3 className="text-base font-semibold tracking-tight text-zinc-800">
            1. Browse species
          </h3>
          <p className="text-zinc-600 leading-relaxed text-sm">
            On the home page, you will find a catalog of all supported species indexed in our current 
            data release. Each card details the species name and {" "}
            <a 
              href="https://www.ncbi.nlm.nih.gov/datasets/genome/" 
              target="_blank" 
              rel="noreferrer" 
              className="text-emerald-600 hover:underline"
            >
              NCBI Genome 
            </a> accession. 
            Click on any species card to open its dedicated cluster browser.
          </p>
        </div>

        {/* Subsection B: Species page */}
        <div className="space-y-2 pl-4 border-l-2 border-zinc-100">
          <h3 className="text-base font-semibold tracking-tight text-zinc-800">
            2. Species page
          </h3>
          <p className="text-zinc-600 leading-relaxed text-sm">
            Once inside a species view, you can browse individual functional clusters through our "cluster of clusters" 
            visualization, where each circle represents a cluster of proteins.
            Further, you can browse or filter the list of clusters by their functional annotation and imputed discription/summary. 
            Finally, if you have a specific protein of interest, you can query its accession in the search bar at the 
            top of each species page. If that protein is assigned to a cluster, it will be recovered by the search and you can do directly to its Protein page.

            The Species page also contains links to directly download the species-wide predicted PPI network, as well as 
            a MEDFORD-format file summarizing the parameters and corresponding outputs of the PHILHARMONIC pipeline run. 
          </p>
        </div>

        {/* Subsection C: Cluster page */}
        <div className="space-y-2 pl-4 border-l-2 border-zinc-100">
          <h3 className="text-base font-semibold tracking-tight text-zinc-800">
            2. Species page
          </h3>
          <p className="text-zinc-600 leading-relaxed text-sm">
            The cluster is the core output of the PHILHARMONIC pipeline. The cluster page displays key information about each cluster,
            including its overall annotation and summary, its size, and the number of predicted PPI edges. 
            The PPI network of proteins in that cluster is also displayed, ad individual proteins are clickable. Finally,
            A list of all {" "}
            <a 
              href="https://amigo.geneontology.org/" 
              target="_blank" 
              rel="noreferrer" 
              className="text-emerald-600 hover:underline"
            >
              GO terms 
            </a> assigned to any proteins and a list of all proteins in the cluster are included.
          </p>
        </div>

        {/* Subsection D: Protein page */}
        <div className="space-y-2 pl-4 border-l-2 border-zinc-100">
          <h3 className="text-base font-semibold tracking-tight text-zinc-800">
            4. Protein page
          </h3>
          <p className="text-zinc-600 leading-relaxed text-sm">
            The protein pages lists the annotations for a single protein, including all {" "}
            <a 
              href="https://amigo.geneontology.org/" 
              target="_blank" 
              rel="noreferrer" 
              className="text-emerald-600 hover:underline"
            >
              GO terms 
            </a> and {" "}
            <a 
              href="https://www.ebi.ac.uk/interpro/entry/pfam/" 
              target="_blank" 
              rel="noreferrer" 
              className="text-emerald-600 hover:underline"
            >
              Pfam 
            </a> domains. 
            This page also links out to the correspodning {" "}
            <a 
              href="https://www.ncbi.nlm.nih.gov/protein/" 
              target="_blank" 
              rel="noreferrer" 
              className="text-emerald-600 hover:underline"
            >
              NCBI Protein 
            </a> page for that protein, as well as linking Background
            to the protein's assigned cluster.
          </p>
        </div>      

        {/* Subsection D: Protein page */}
        <div className="space-y-2 pl-4 border-l-2 border-zinc-100">
          <h3 className="text-base font-semibold tracking-tight text-zinc-800">
            4. Downloads
          </h3>
          <p className="text-zinc-600 leading-relaxed text-sm">
            The predicted PPI network for a given species can be downloaded from its Species page.
            Further, the Download link at the top of the website goes to an FTP-style interface where 
            all PPI and annotation files are available for download.
          </p>
        </div>   
      </section>

      {/* Section 3: Contributing */}
      <section className="space-y-3">
        <h2 className="text-xl font-semibold tracking-tight text-zinc-800">
          Contributing
        </h2>
        <p className="text-zinc-600 leading-relaxed text-sm">
          We welcome contributions and feedback on PHILHARMONIC DB. If you have questions, 
          notice dataset errors, or want to contribute new species, please reach out to us by email at{" "}
          <a 
            href="mailto:philharmonic-db@mit.edu?subject=PHILHARMONIC%20DB%20Contribution"
            className="text-emerald-600 hover:underline font-medium"
          >
            philharmonic-db@mit.edu
          </a>.
        </p>
      </section>
    </div>
  );
}