import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Link from "next/link";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "PHILHARMONIC DB",
  description:
    "Browse PHILHARMONIC protein-interaction clusters and functional annotations across species.",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}>
      <body className="min-h-full flex flex-col font-sans">
        <header className="border-b border-zinc-200 bg-white">
          <div className="mx-auto max-w-6xl px-6 py-4 flex items-center gap-3">
            <Link href="/" className="text-lg font-semibold tracking-tight">
              PHILHARMONIC<span className="text-emerald-600"> DB</span>
            </Link>
            <span className="text-sm text-zinc-400">
              protein-interaction cluster browser
            </span>
          </div>
        </header>
        <main className="flex-1 mx-auto w-full max-w-6xl px-6 py-8">{children}</main>
        <footer className="border-t border-zinc-200 bg-white">
          <div className="mx-auto max-w-6xl px-6 py-4 text-xs text-zinc-500">
            Data generated by the PHILHARMONIC pipeline.
          </div>
        </footer>
      </body>
    </html>
  );
}
