import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Link from "next/link";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "PHILHARMONIC DB",
  description:
    "Browse PHILHARMONIC protein-interaction clusters and functional annotations across species.",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}>
      <body className="min-h-full flex flex-col font-sans">
        <header className="border-b border-zinc-200 bg-white">
          <div className="mx-auto max-w-6xl px-6 py-4 flex items-center justify-between">
            {/* Branding Details */}
            <div className="flex items-center gap-3">
              <Link href="/" className="text-lg font-semibold tracking-tight">
                PHILHARMONIC<span className="text-emerald-600"> DB</span>
              </Link>
              <span className="text-sm text-zinc-400 hidden sm:inline">
                protein-interaction cluster browser
              </span>
            </div>

            {/* Top Navigation Links */}
            <nav className="flex items-center gap-6 text-sm font-medium">
              <Link 
                href="/about" 
                className="text-zinc-600 hover:text-emerald-600 transition-colors"
              >
                About
              </Link>
              <a 
                href="/preprocessed_data/species" 
                className="text-zinc-600 hover:text-emerald-600 transition-colors"
              >
                Downloads
              </a>
            </nav>
          </div>
        </header>

        <main className="flex-1 mx-auto w-full max-w-6xl px-6 py-8">{children}</main>

        <footer className="border-t border-zinc-200 bg-white">
          <div className="mx-auto max-w-6xl px-6 py-4 text-xs text-zinc-500">
            Data generated by the{" "}
            <a 
              href="https://github.com/samsledje/philharmonic" 
              target="_blank" 
              rel="noreferrer" 
              className="text-emerald-600 hover:underline"
            >
              PHILHARMONIC pipeline
            </a>. ({" "}
            <a
              href="https://www.biorxiv.org/content/10.1101/2024.10.25.620267v3"
              target="_blank"
              rel="noreferrer"
              className="text-emerald-600 hover:underline"
            >
              preprint
            </a>)
          </div>
        </footer>
      </body>
    </html>
  );
}